version: '3.8'

services:
  db:
    image: atomhub.openatom.cn/amd64/mysql:5.7.43
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true

volumes:
  mysql_data:
